### ISSUE TITLE
Go through the startup marketing checklist and ensure Swetrix complies with that

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/swetrix#301]
The original checklist is located at: https://draft.dev/learn/marketing-checklist
-----------------------------
## Pre-Launch

Marketing starts long before you launch. Market research, planning, and preparation are critical parts of any marketing strategy.

### Competitor Research

> _I have been up against tough competition all my life. I wouldn't know how to get along without it._ - Walt Disney

- [x] Make a list of competitors (see [this list of tools to research competitors](https://draft.dev/learn/competition-research-tools)).
- [x] Competitor data to collect:
  - [x] Link to their website.
  - [ ] "One-liners" and taglines competitors use.
  - [ ] Pricing and business model.
  - [ ] Blog/RSS link.
  - [ ] Social media links.
  - [ ] Key employees on social media.
- [ ] Subscribe to RSS feeds of your competitors' blogs.
- [ ] Follow your competitors and their key employees on social media.
- [ ] Monitor competitors' websites for changes.
- [ ] Site monitoring tools to try:
  - [ ] [Deep Dive Duck](https://deepdiveduck.com/)
  - [ ] [Versionista](https://versionista.com/)
- [ ] Subscribe to industry newsletters, magazines, trade journals etc.
- [ ] Use [Google Trends](https://trends.google.com/trends/) to do initial demand and search volume research.

### Customer Research

> _If we knew what we were doing it wouldn’t be called research._ - Albert Einstein

- [ ] Find people in your contact list who might be future customers. Get their feedback on your idea.
- [ ] Attend meetups or conferences for your target market.
- [ ] Meet another entrepreneur who has a similar or competitive product.
- [ ] Make a list of your competitors' customers:
  - [ ] Check competitors' Twitter followers, mentions.
  - [ ] Look through their Facebook fans.
  - [ ] Find people who follow them on Linkedin.
  - [ ] Check their website. Some companies list customer stories on their websites.
- [ ] Reach out to your competitors' customers, find out what they like/don't like.
- [ ] Create an "early access" list for potential future customers.

### PR (Public Relations) Preparations

- [ ] Create list of tech, startup, and industry blogs.
- [ ] Create list of local small business journals.
- [ ] Create list of local bloggers and journalists in your industry.
- [ ] Create a "Media Kit" page ([check out this example](https://www.kickresume.com/mediakit/)).

### Website Setup

- [x] Come up with a name and domain name.
- [x] Write a site tagline and elevator pitch.
- [x] Create a logo (see [this list of logo creation tools](https://draft.dev/learn/logo-creation-tools)).
- [x] Set up a landing page (see [this list of landing page tools](https://draft.dev/learn/tools/landing-pages)).
- [x] Create "About" and "Contact" pages.
- [x] Create Pricing page (see [this list of pricing models](https://taprun.com/methods/)):
- [x] Consider/test various pricing options:
  - [x] Create a free or trial tier for your paid product.
  - [x] Offer a 100% satisfaction/money-back guarantee.
  - [x] Make product invite-only to start.
  - [x] Offer free/discounted access for early adopters/beta testers.
- [x] Add social media follow links to landing page.
- [x] Set up analytics to learn about who signs up, bounces, etc.
- [x] Analytics platforms to try:
  - [x] [Swetrix](https://swetrix.com) :)
- [x] Set up error logging, monitoring, capturing, etc.
- [x] Error monitoring tools to try:
  - [x] [Bugsnag](https://www.bugsnag.com/)
  - [x] [Rollbar](https://rollbar.com/)
  - [x] [Sentry](https://sentry.io/welcome/)
- [x] Set up on-site messaging to capture leads and engage customers as they land on your site (see our [list of live customer chat tools](https://draft.dev/learn/customer-chat-tools)).
- [x] Test your website for common SEO, speed, and security problems like broken links, missing page titles and insecure pages (see [Checkbot](https://www.checkbot.io)).

### Email Setup

*[See this list of email marketing tools](https://draft.dev/learn/tools/email-marketing) for services that make managing email easier.*

> _Email is the Jason Bourne of online: somebody’s always trying to kill it. It can’t be done._ - Unknown

- [x] Set up email address to send and receive emails.
- [x] Set up email list and signup form.
- [x] Create a standard email template for your brand.
- [x] Create transactional emails for when users sign up/purchase.

### Blog Setup

> _Content Marketing is all the marketing that’s left._ - Seth Godin

- [ ] Choose a blogging platform (see this list of [blogging platforms for your startup](https://draft.dev/learn/startup-blogging-platforms)).
- [ ] Research [keywords that you'd like your site to rank for](https://draft.dev/learn/topic-clusters).
- [ ] Keyword research tools to try:
  - [Ahrefs](https://ahrefs.com/)
  - [SpyFu](https://www.spyfu.com/)
  - [SEMrush](https://www.semrush.com/)
  - [KeywordTool.io](http://keywordtool.io/)
  - [Moz Keyword Explorer](https://moz.com/explorer)
  - [KWFinder](https://kwfinder.com/)
  - [Google Keyword Research](https://adwords.google.com/home/tools/keyword-planner/)
  - [Ubersuggest](https://neilpatel.com/ubersuggest/)
- [ ] Create anchor posts or pages for keywords you'd like to rank for.
- [ ] Have a blog post brainstorming session (see this [big list of blog post ideas](https://draft.dev/learn/startup-blog-ideas)).
- [ ] Add email signup form or link to all blog posts.
- [ ] Add social media follow links to all blog posts.

### Social Media Setup

> _Social media is the ultimate equalizer. It gives a voice and a platform to anyone willing to engage._ - Amy Jo Martin, CEO of Digital Royalty

- [x] Search for availability of names on social networks using [KnowEm](https://knowem.com/).
- [x] Choose the social media accounts you'll use:
  - [ ] Facebook
  - [x] Twitter
  - [x] Linkedin
  - [ ] Pinterest
  - [ ] Instagram
  - [ ] Snapchat
  - [ ] YouTube
- [x] Standardize profile image, background photo, links and call to action across social channels.
- [x] Consider putting premium content behind "[pay with a tweet](https://www.paywithatweet.com/)".

## Post-Launch

Once you launch, the real fun begins! Whether you go out with a bang or you gradually grow your userbase over months, getting customer feedback is essential for building a successful startup.

### Free Promotional Channels

> _I don't care how much money you have, free stuff is always a good thing._ - Queen Latifah

- [x] Post your product on directories and review sites (Matt McCaffrey has compiled [a great list on Github](https://github.com/mmccaff/PlacesToPostYourStartup) or you can use a service like [Instaaa](https://www.instaaa.com/)).
- [x] Write and distribute a Press Release (here's a [comprehensive guide from Wajeez](http://www.wajeez.com/writing-quick-press-releases/), or you can [use one of these distribution tools](https://draft.dev/learn/press-release-tools)).
- [ ] Write and distribute an eBook, exchange it for email signup.
- [ ] Write and distribute a white paper, exchange it for email signup.
- [ ] Give free access to influential bloggers in the industry.
- [ ] Build a "best of" page with your best blog posts that you wrote or contributed to other sites (ProBlogger calls this a "[Sneeze Page](https://problogger.com/create-a-sneeze-page-and-propel-readers-deep-within-your-blog/)").
- [x] Make sure all blog posts have high quality images (see [this list of free stock image sites](https://draft.dev/learn/tools/stock-images)).
- [ ] Create an online course or guide around your product/industry (be sure to [check out this list of course management tools](https://draft.dev/learn/course-creation-tools)).
- [ ] Run an [influencer marketing campaign](https://www.reddit.com/r/startups/comments/7aap5u/influencer_marketing_summary_of_12_articles/).
- [ ] Run a link-building campaign.
- [ ] Share the story of how you started your business on [Starter Story](https://starterstory.com) - it's free and you get a do-follow backlink.
- [ ] Try other link building strategies:
  - [ ] [Skyscraper campaign](http://backlinko.com/skyscraper-technique)
  - [ ] [Ego baiting](http://pointblankseo.com/egobait-guide)
  - [ ] Interview/expert Q&A post
  - [ ] Guest posting
  - [ ] Broken link building
  - [ ] Get interviewed on podcasts
  - [ ] Become a source on [Help a Reporter Out](https://www.helpareporter.com/)
  - [ ] [More strategies on Backlinko.com](http://backlinko.com/link-building)

### Paid Promotional Channels

> _You must spend money to make money._ - Plautus, Ancient Roman playwright

- [ ] Try a few social, search, and commission-based advertising platforms.
- [ ] Sponsor a local meetup or conference for your target customers.
- [ ] Sponsor podcasts your customers might be listening to.
- [ ] Sponsor/advertise an industry newsletter.
- [ ] Set up a user referral marketing system/platform:
  - [ ] [Harry's Prelaunchr (free, open source)](https://github.com/harrystech/prelaunchr)
  - [ ] [CleverTap (offers a free tier)](https://clevertap.com/)
  - [ ] [Expect Referrals](http://expectreferrals.com/pricing/)
  - [ ] [Frederick](https://www.hirefrederick.com/)
  - [ ] [Genius Referrals](http://www.geniusreferrals.com/)
  - [ ] [InviteBox](https://invitebox.com/)
  - [ ] [InviteReferrals](http://www.invitereferrals.com/)
  - [ ] [Referral Candy](https://www.referralcandy.com/)
  - [ ] [Viral Loops](https://viral-loops.com/)
  - [ ] [Girafi](https://girafi.co/)
- [ ] Run an engagement contest with prizes or free products for winners.
- [ ] Run [retargeting ads](https://retargeter.com/what-is-retargeting-and-how-does-it-work) to target users who have been to your site before.

## Recurring

Much of marketing is staying consistent over time. While you need to know that a tactic is viable, you might have to stick with it for weeks to see real results.

### Blogging

> _Blogging is like work, but without coworkers thwarting you at every turn._ - Scott Adams, Creator of Dilbert

- [x] Build/update publishing calendar for your blog.
- [x] Regularly post blog posts on your blog(s).
- [ ] Solicit guest posts from early customers and fans of your product.
- [ ] Repurpose existing blog posts:
  - [ ] Record/post video of you reading the post on YouTube.
  - [ ] Turn posts into a podcast.
  - [ ] Create an infographic based on the post.
  - [ ] Create a presentation of your post.
- [ ] Promote your blog content (see [this big checklist for more promotional ideas](https://draft.dev/learn/promotion):
  - [ ] Send post to your email list.
  - [ ] Promote on your social media.
  - [ ] Email friends and relatives, ask them to share if relevant.
  - [ ] Send to other bloggers for feedback, ask to share if they like it.
  - [ ] Add your latest blog post or landing page to your email signature.
  - [ ] Submit your post to relevant aggregators and niche communities.
- [ ] [Refresh old blog posts every 6-12 months](https://draft.dev/learn/refreshing-blog-posts)

### Email

> _Any email that contains the words 'important' or 'urgent' never are, and annoy me to the point of not replying out of principle._ - Markus Persson, aka "Notch", creator of Minecraft

- [ ] Send a regular email newsletter with blog posts, use cases, customer stories, etc.
- [ ] Promote email list on social media.
- [ ] Send 20 cold emails per week to connect with early customers and get direct feedback.
- [ ] Send new users a personal email introducing yourself.

### Social Media

> _We have technology, finally, that for the first time in human history allows people to really maintain rich connections with much larger numbers of people._ – Pierre Omidyar, Founder of eBay

- [x] Schedule regular social media content (try these [social media tools to help automate the social media process](https://www.sideprojectchecklist.com/2017/social-media-tools)).
- [x] Social media content ideas to try:
  - [ ] Show what happening "behind the scenes" (eg: pictures of your workspace, in-development features, etc.).
  - [x] Blog posts from your blog (or partners' blogs).
  - [ ] Special offers or discounts.
  - [ ] Relevant news, advice, or blogs.
  - [ ] Funny or inspiring quotes.
  - [ ] Polls or questions for your followers.
  - [ ] Suggested books.
  - [ ] Useful tools or websites.
- [ ] Join Facebook and Linkedin groups where your product might be beneficial.
- [ ] Send exclusive offers to LinkedIn/Facebook Group owners.
- [ ] Join Twitter chats related to your industry/product.
- [ ] Search Twitter for people talking about issues you're solving with your project and interact with them.
- [ ] Give early users discounts for taking pics with your product.

### Public Relations

> _The art of publicity is a black art; but it has come to stay, and every year adds to its potency._ – Thomas Paine

- [ ] Ask bloggers with list articles to add your site to their content.
- [ ] Reach out to small business journals, reporters, bloggers. Inform and ask for coverage.
- [ ] Reach out to podcasters, try to get featured on their show.
- [ ] Find professors and students with `.edu` sites to link to your content (good for SEO).
- [ ] Find reviews or lists of similar products. Ask to be added or leave a comment about your product.
- [ ] Guest post on other blogs:
  - [ ] Build a list of blogs that are a good fit for your product and accept guest posts. Save their contact form/information.
  - [ ] Write a few posts on your own blog first (to use as a demonstration).
  - [ ] Create a list of "pitches," blog post ideas with a title and one paragraph summary that might grab bloggers.
  - [ ] Pitch the blogs one idea each. See what they respond to.
  - [ ] Help promote your posts via social media, email lists, etc.
  - [ ] Reach back out in a month and try another pitch. Try to become a "regular"
- [ ] Join and participate in forums related to your product or industry.

### External Sites

- [ ] Answer relevant questions on Q&A community sites (check back regularly):
  - [ ] [Stack Overflow](https://stackoverflow.com/)
  - [ ] [Quora](https://www.quora.com/)
  - [ ] Industry or geographically specific forums
  - [x] [Product Hunt](https://www.producthunt.com/) For more information on how to launch here, [read this](https://blog.producthunt.com/how-to-launch-on-product-hunt-7c1843e06399).

- [ ] Leave comments on Slideshare presentations.
- [ ] Review industry-related books on Amazon, Goodreads.
- [ ] Register to be [notified of topics on Reddit and Hacker News with F5Bot](/2018/f5bot-tracking).
- [ ] Create/publish presentations relevant to your industry:
  - [ ] [Google Slides](https://docs.google.com/presentation/)
  - [ ] [Prezi](https://prezi.com/)
  - [ ] [Slides.com](https://slides.com/)
  - [ ] [Slideshare](https://www.slideshare.net/)

## Optimizations

After you've kicked off your marketing engine and you start to see results, it's time to optimize. The following ideas will help you get started, but optimizing your marketing efforts is a never-ending challenge.

- [ ] Run a customer poll (can also generate content for your blog or social media channels).
- [ ] Create a side project to promote your startup ([read more](https://medium.com/swlh/side-product-marketing-is-the-new-king-a75c4ed0c0c5)).
- [ ] A/B test your landing/payment pages.
- [ ] A/B test email newsletters and promotions.
- [ ] Implement [Twitter cards](https://dev.twitter.com/cards/overview) on your blog posts.
- [ ] Implement [rich snippets in Google search results](https://developers.google.com/search/docs/guides/mark-up-content).
- [ ] Analyze user signup flow ([check out the teardowns here](http://www.useronboard.com/)).
- [ ] Test your website on multiple platforms, make sure speed is good.
- [ ] Use [Website Grader](https://website.grader.com/) to pinpoint website improvements.
- [x] Create and track weekly traffic and growth goals.
- [ ] Time social media posts and email newsletters to when your audience is most likely to respond.
- [ ] Make sure each page on your site has a clear call-to-action.
- [ ] Audit and improve your conversion rate (see [this checklist for detailed steps you can take](http://www.conversionchecklist.org/))
- [ ] Set up automatic analytics reports to be emailed to you each week.
- [ ] Experiment with various signup form locations, colors, and sizes.
- [ ] Add "Exit Intent" popup to your blog/site.
- [x] Create an FAQs page.
- [x] Verify your website's tags are correct with [Google Tag Assistant](https://get.google.com/tagassistant/).
- [ ] Watch a first time user use your product.
- [ ] Collect and display testimonials from happy users.
- [ ] Survey or poll your users for feedback (see our [list of survey tools for lots of great options at any budget](https://draft.dev/learn/tools/surveys) or this [list of Google Forms alternatives](https://www.karllhughes.com/posts/google-forms-alternatives)).
- [ ] Use [Monkey Test It](https://monkeytest.it/) to find bugs and broken links of your site. Set up an alert to notify you on breakage.
- [ ] Use [Checkbot](https://www.checkbot.io) on your website to test for and fix SEO, speed and security problems.
- [ ] Follow [the steps here](https://gdprchecklist.io/) to ensure GDPR compliance.
