### ISSUE TITLE
Selfhosted v3.3.0 - to-do list

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/swetrix#338]
The following tasks must be completed before the release of the next selfhosted version:
 - [x] Add Clickhouse configuration files to selfhosting repo (done at https://github.com/Swetrix/selfhosting/pull/10)
 - [x] Add `IS_PRIMARY_NODE` variable support to selfhosted
 - [x] https://github.com/Swetrix/swetrix/issues/329
 - [x] https://github.com/Swetrix/swetrix/issues/341
 - [x] https://github.com/Swetrix/swetrix/issues/339
 - [x] https://github.com/Swetrix/swetrix/issues/340
 - [x] https://github.com/Swetrix/swetrix/issues/343
